class OBDomesticVRPConsentRequest {

}


class Data {

}

OBDomesticVRPConsentRequest .d. Data

!include ../OBDomesticVRPControlParameters/OBDomesticVRPControlParameters.puml
!include ../OBDomesticVRPInitiation/OBDomesticVRPInitiation.puml

Data .. "[1..1] ControlParameters" OBDomesticVRPControlParameters 
Data .. "[1..1] Initiation" OBDomesticVRPInitiation 




