AddressType : (0..1) OBAddressTypeCode  
Department : (0..1) Max70Text  
SubDepartment : (0..1) Max70Text
StreetName : (0..1) Max70Text  
BuildingNumber : (0..1) Max16Text  
PostCode : (0..1) Max16Text  
TownName : (0..1) Max35Text  
CountrySubDivision : (0..1) Max35Text  
Country : (0..1) CountryCode
AddressLine : (0..7) Max70Text  
